person:
  nickName: allen
  age: 18
  brith: 2019/12/01
  maps: {k1: v1,k2: v2}
  lists:
    - man
    - weman
    -

keyboard:
  name: 迈从
  logo: MCHOSE
  isMechanical: true
  axis: red
  keycaps: pbt
  keysNum: 99